# ~/.config/starship.toml

add_newline = false
command_timeout = 1000
format = """$os$username$hostname$kubernetes$conda$directory$git_branch """
#format = """$os$username$hostname$kubernetes$conda$directory$git_branch$git_status"""

# Drop ugly default prompt characters
[character]
success_symbol = ''
error_symbol = ''

# ---

[os]
format = '[$symbol](dimmed white) '   
disabled = false

[os.symbols]
Windows = 'î˜ª '
Arch = 'ó°£‡'
Ubuntu = 'ïŒ›'
Macos = 'ó°€µ'

# ---y

# Shows the username
[username]
style_user = 'white dimmed'
style_root = 'black dimmed'
format = '[$user]($style)'
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '@[$hostname](dimmed yellow)'
disabled = false

# Shows current directory
[directory]
truncation_length = 1
truncation_symbol = 'â€¦/'
home_symbol = 'ó°‹œ ~'
read_only_style = '197'
read_only = 'ï€£ '
format = '[$path]($test)[$read_only]($read_only_style)'

# Shows current git branch
[git_branch]
symbol = 'ï‡’'
format = '{[$symbol$branch]($style)}'
# truncation_length = 4
truncation_symbol = 'â€¦/'
style = 'dimmed green'

# Shows current git status
[git_status]
format = '([\($all_status$ahead_behind\)]($style) )'
style = 'dimmed green'
conflicted = '[ïª confliced=${count}](red)'
up_to_date = '[ó°˜½ up-to-date](green)'
untracked = '[ó°‹— untracked=${count}](red)'
ahead = 'ï‚ª ahead=${count}'
diverged = 'ï‚ª ahead=${ahead_count} ï‚« behind=${behind_count}'
behind = 'ï‚« behind=${count}'
stashed = '[ïŠ‹ stashed=${count}](green)'
modified = '[ó°›¿ modified=${count}](yellow)'
staged = '[ó°— staged=${count}](green)'
renamed = '[ó±¸ renamed=${count}](yellow)'
deleted = '[ó°¶ deleted=${count}](red)'

# Shows kubernetes context and namespace
[kubernetes]
disabled = false
# Context + character only if non-empty, namespace always
format = '([ó±ƒ¾$context]($style))[$namespace]($style)'
style = "dimmed purple"
context_aliases = { "docker-desktop" = "" }


[conda]
symbol = "ğŸ…’"
style = "dimmed green"
format = "[$symbol$environment]($style)"
# ignore_base = false
disabled = false

# ---

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
